name: Deploy to Glitch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync with Glitch
      run: |
        git remote add glitch https://de008625-dd23-41d0-9861-222fb406bd15@api.glitch.com/git/somsoc
        git push glitch main --force
